### ISSUE TITLE
thermometry Data Node Server crashes during operation

### ISSUE THREAD

**Issue by BrianJKoopman** [simonsobs/sisock#30]
Both Yale and UCSD have seen the thermometry data node server crash at times with the following output:
```
2019-04-22T17:19:16+0000 Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/autobahn/wamp/websocket.py", line 95, in onMessage
    self._session.onMessage(msg)
  File "/usr/local/lib/python3.7/site-packages/autobahn/wamp/protocol.py", line 1017, in onMessage
    raise ProtocolError("INTERRUPT received for non-pending invocation {0}".format(msg.request))
autobahn.wamp.exception.ProtocolError: INTERRUPT received for non-pending invocation 238486

2019-04-22T17:19:16+0000 session closed with reason wamp.close.transport_lost [WAMP transport was lost without closing the session before]
2019-04-22T17:19:16+0000 disconnected
2019-04-22T17:19:16+0000 Main loop terminated.
```

I'm not sure what causes it yet, or how to reproduce it.

**Comment by BrianJKoopman** [comment]
Latest versions of the containers include autobahn version 19.6.2. Closing issue.
